Added README , SUPPORT, SECURITY, CODE_OF_CONDUCT, CONTRIBUTING
Seagate/cortx-fs pull request #27
Opened 2020-10-05 15:13 UTC by Saumya-Sunder

Added README , SUPPORT, SECURITY, CODE_OF_CONDUCT, CONTRIBUTING 

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

2020-10-06 04:39 UTC, sachinpunadikar commented on README.md
> +# CORTX-FS
keep it CORTXFS

2020-10-06 04:39 UTC, sachinpunadikar commented on README.md
> +The CORTX File System (FS) framework on top of the cloud object storage is the entry point for file access protocols (like NFS, CIFS). The CORTX-FS makes use of the NSAL and DSAL libraries to provide
CORTX-FS  -> CORTXFS

2020-10-06 04:40 UTC, sachinpunadikar requested changes
Make sure that we are calling it CORTXFS

2020-10-29 14:04 UTC, Saumya-Sunder commented on README.md
> +# CORTX-FS
Done

2020-10-29 14:04 UTC, Saumya-Sunder commented on README.md
> +The CORTX File System (FS) framework on top of the cloud object storage is the entry point for file access protocols (like NFS, CIFS). The CORTX-FS makes use of the NSAL and DSAL libraries to provide
Done

2020-10-29 14:11 UTC, sachinpunadikar approved these changes
+1

2020-11-02 18:50 UTC, s-arya approved these changes
LGTM

2020-11-03 04:46 UTC, merged